allowBuilds:
  bcrypt: false
  unrs-resolver: false
minimumReleaseAgeExclude:
  - '@redis/bloom@6.0.1'
  - '@redis/client@6.0.1'
  - '@redis/json@6.0.1'
  - '@redis/search@6.0.1'
  - '@redis/time-series@6.0.1'
  - redis@6.0.1
